data:extend({
	{
		type = "bool-setting",
		name = "wret-overload-keep-vanilla-sprite-mk1",
		setting_type = "startup",
		default_value = false,
		order = "a0",
	},
	{
		type = "bool-setting",
		name = "wret-overload-enable-beaconmk2",
		setting_type = "startup",
		default_value = true,
		order = "a1",
	},
	{
		type = "bool-setting",
		name = "wret-overload-enable-beaconmk3",
		setting_type = "startup",
		default_value = true,
		order = "a2",
	},
	{
		type = "bool-setting",
		name = "wret-overload-enable-notnotmelon-style",
		setting_type = "startup",
		default_value = false,
		order = "yyyyy",
	},
	{
		type = "bool-setting",
		name = "wret-overload-enable-lamp-tile-detection",
		setting_type = "startup",
		default_value = false,
		order = "zzzzz",
	},
	{
        type = "bool-setting",
        name = "classic-beacon-do-high-res",
        setting_type = "startup",
        default_value = true,
		hidden = true,
		forced_value = true,
		order = "doki doki waku waku",
    },
	{
        type = "bool-setting",
        name = "wret-change-K2-beacon",
        setting_type = "startup",
        default_value = true,
		order = "mK2",
    },
	{
        type = "bool-setting",
        name = "wret-block-FE-beacons",
        setting_type = "startup",
        default_value = true,
		order = "mFE1",
    },
	{
        type = "bool-setting",
        name = "wret-FE-beacons-modification",
        setting_type = "startup",
        default_value = true,
		order = "mFE2",
    },
	{
        type = "bool-setting",
        name = "wret-block-bob",
        setting_type = "startup",
        default_value = true,
		order = "mbob1",
    },
	{
        type = "bool-setting",
        name = "wret-change-bob",
        setting_type = "startup",
        default_value = true,
		order = "mbob2",
    },
})